language: node_js
sudo: required

node_js:
  - "10"

services:
 - docker

os:
  - linux

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
